### ISSUE TITLE
issuesDev#1 Mostrar100NumerosFor

### ISSUE THREAD

**Issue by enanibus** [enanibus/PracticasJava#1]
Mostrar los 100 primeros números enteros en consola con un bucle for.
Bajar la rama develop, el paquete `practicas1` contiene la clase `Mostrar100NumerosWhile` que muestra los números pero con un bucle while.

Se trata de que  hacer una clase nueva `Mostrar100NumerosFor`, con una estructura de bucle for.

**Comment by manuchi** [comment]
Me bajo el .zip y lo intento hacer desde ahí no?

**Comment by enanibus** [comment]
Bájate el .zip, haces una clase `Mostrar100NumerosFor`, como es debido (es broma) y la copias aquí si no consigues hacerlo de otra forma. 
Seguimos en contacto.

**Comment by manuchi** [comment]
Lo he intentado, me ha salido, pero unos números enormes que no paran de crecer y crecer

**Comment by enanibus** [comment]
Hola Manu
??
Eso suena a bucle infinito
Lo miro y te cuento

Enviado desde mi iPhone
