### ISSUE TITLE
issuesDev#3 PiedraPapelTijeras

### ISSUE THREAD

**Issue by enanibus** [enanibus/PracticasJava#3]
## Objetivo

Se trata de hacer una clase nueva `PiedraPapelTijeras` para jugar al juego del mismo nombre, cuyas reglas son:

Se parte de tres objetos que eligen al azar dos jugadores, primero uno elige uno y luego el otro jugador elige otro y se contrasta el resultado según las siguientes reglas:
- La piedra gana a las tijeras
- Las tijeras ganan al papel
- El papel gana a la piedra

En caso de elegir el mismo objeto, se produce un empate, que se resolverá jugando una nueva partida.
### Pistas
- Para realizar la tarea nos basamos en la clase que hace el juego de adivinar un número entre 1 y 100, `AdivinarNumero100`, la cual explicaremos y estudiaremos en detalle
- Haremos un bucle principal para jugar hasta que se quiera y dentro se harán tantas partidas como queramos
- Se deja el esqueleto de la clase con variables ya declaradas
- Se crea una variable de tipo enumerado `enum opciones = {Piedra, Papel, Tijeras}`. A partir de la posición, 0, 1,2, se sabe si es Piedra, Papel o Tijeras
- Se crean unas constantes de tipo entero para elegir aleatoriamente entre 0, 1 y 2 
  `int piedra = 0; int papel = 1; int tijeras = 2;`
- Se crean dos variables de tipo `int` para guardar los valores que han elegido el jugador humano y el jugador máquina, respectivamente: `int opcionHumano`, `int opcionMaquina` 
- Se pide al usuario que elija entre los tres valores, Piedra, Papel o Tijeras y se guarda en la variable `opcionHumano`
- Se incluye un código que calcula un número aleatorio entre 0, 1 y 2, y se guarda en la variable `opcionMaquina`
- A partir de aquí, a base de condiciones, se contrastan los valores, por un lado, el introducido por el usuario que esta en la variable `opcionHumano` y por otro, el valor elegido aleatoriamente por la máquina, que está en `opcionMaquina`
  A base de expresiones `if (condicion) { ... } else { if (condicion) { ... } else { ... }  }` anidadas, se evalúa quién gana:

Ejemplo: 

``` java
if (opcionUsuario == (opciones.Piedra.ordinal()))  {
         if (opcionMaquina == (opciones.Piedra.ordinal())) {
        System.out.println("---------EMPATE---------");
    }
...
...
}
```

También se puede hacer así, a través de las constantes PIEDRA, PAPEL, TIJERA, el objetivo es ver las constantes y las variables de tipo `enum`:

``` java
if (opcionUsuario == PIEDRA)  {
         if (opcionMaquina == PIEDRA) {
        System.out.println("---------EMPATE---------");
    }
...
...
}
```

**Comment by enanibus** [comment]
Manu, consulta la clase `AdivinarNumero100` de la rama **develop** para ver el código. Mira el código y estúdialo detenidamente. Ejecútalo cuantas veces sea necesario para que lo vayas entendiendo.

Suerte!

**Comment by manuchi** [comment]
Estoy en ello

**Comment by manuchi** [comment]
Por ahora he hecho que si es tijera vs tijera y papel vs papel que ponga ------empate------. Ahora estoy con lo de import java.util.Scanner

**Comment by manuchi** [comment]
Pero tengo 2 errores. No me detecta TIJERAS como variable

**Comment by enanibus** [comment]
Manu, he visto tu mensaje.

Lee detenidamente cuantas veces sea necesario las pistas/instrucciones que te doy. La clave es entender perfectamente el ejemplo `AdivinarNumero100` porque en realidad es muy, pero que muy parecido al que hiciste el otro día en clase. Pregunta todo lo que no entiendas, pero el ejemplo es muy claro. Hace dos bucles, uno externo, para jugar tantas partidas como quiera el usuario y otro bucle interno, donde se juega la partida de adivinar el número. Si te fijas, esta parte del bucle interno es análogo al que hiciste en clase.
En cuanto al Piedra/Papel/Tijeras, se trata de que, una vez **entiendas** lo que hay que hacer, simplemente es hacer condiciones if else anidadas para imprimir un mensaje de quién ha ganado.
Sin ver tu código, si no te detecta TIJERAS es porque el nombre al que te refieras no exista; mira a ver si es TIJERA la constante y no TIJERAS. Hazlo con constantes, como te pongo en el ejemplo.

Ánimo tío que esto de la programación es eso, entender y plasmarlo luego en el código. No tengas prisa, hay que consolidar los conocimientos y tenerlos claros, por eso se empieza con tipos de datos, constantes, condiciones, bucles, ...

Seguimos en contacto.
